#!/usr/bin/env python3
"""Generate a deck's progress-bar section map and inject it into its frontmatter.

The theme's progress bar knows how far into the deck a slide is (Marpit stamps
the numbers on every section), but CSS on slide *n* cannot know where the other
sections start and end. So the bar can only be one colour at a time.

This computes that missing information once per deck and hands it to the theme
as a static gradient: each section's colour occupies its own share of the bar's
width, in deck order. The bar then *accumulates* — walk into section 3 and the
stretches for sections 1 and 2 stay on screen in their own colours, with the
current section growing at the right-hand end.

Input is the rendered `slides.html`, not the markdown: Marp has already resolved
carried `<!-- class: ... -->` directives there, so there is no directive parsing
to get wrong. Build the HTML first, run this, then rebuild both outputs.

    marp slides.md --theme <theme> --allow-local-files --html -o slides.html
    python <skill-dir>/scripts/build-progress-map.py slides.md
    marp slides.md ... -o slides.html && marp slides.md ... -o slides.pdf

The map bakes LITERAL hex into the deck, so after changing any --inno-b* colour
in the theme, re-run this for every deck — a theme edit alone does not reach it.

The injected block is delimited by markers and is rewritten in place on every
run, so re-running after adding slides is safe and produces no duplicates.
"""

import argparse
import re
import sys
from pathlib import Path

BEGIN = "/* progress-map: generated by build-progress-map.py — do not edit */"
END = "/* end progress-map */"

SECTION_RE = re.compile(r'data-marpit-pagination="(\d+)" style="([^"]*)"')
CLASS_RE = re.compile(r"--class:([^;]*)")
# Matches b1-b8 and the darker per-area variants b1d-b6d. The trailing "d"
# must be inside the captured group, or a b1d section resolves to plain b1
# and the part boundary it was written to mark vanishes from the bar.
BLOCK_RE = re.compile(r"\bb([1-8]d?)\b")

THEME = Path(__file__).resolve().parent.parent / "themes" / "innopolis.template.css"
TOKEN_RE = re.compile(r"--(inno-(?:b[1-8]d?|green)):\s*(#[0-9a-fA-F]{3,8})\s*;")


def palette() -> dict[str, str]:
    """The theme's section colours, as literal hex.

    Resolved here rather than emitted as `var(--inno-b3)`: the map is one long
    custom property, and a deck's own `style:` block is a fragile place to lean
    on nested substitution. Literal hex also makes the injected block readable
    on its own. Re-run the script after changing the palette.
    """
    if not THEME.exists():
        sys.exit(f"Missing theme: {THEME}")
    return {name: hexval for name, hexval in TOKEN_RE.findall(THEME.read_text(encoding="utf-8"))}


def slide_colors(html: str, colors_by_token: dict[str, str]) -> list[str]:
    """One hex colour per slide, in deck order."""
    out = []
    for _, style in SECTION_RE.findall(html):
        cls = CLASS_RE.search(style)
        block = BLOCK_RE.search(cls.group(1)) if cls else None
        token = f"inno-b{block.group(1)}" if block else "inno-green"
        out.append(colors_by_token[token])
    return out


def runs(colors: list[str]) -> list[tuple[str, int, int]]:
    """Collapse consecutive same-colour slides into (colour, first, last), 1-indexed.

    The cover slide carries no section class and shows no bar, so its share is
    merged into the section that follows it — otherwise every deck's bar opens
    with a stub of brand green.
    """
    out: list[list] = []
    for i, c in enumerate(colors, 1):
        if out and out[-1][0] == c:
            out[-1][2] = i
        else:
            out.append([c, i, i])
    if len(out) > 1 and out[0][1] == 1 and out[0][2] == 1:
        merged = out.pop(0)
        out[0][1] = merged[1]
    return [tuple(r) for r in out]


def gradient(colors: list[str]) -> str:
    n = len(colors)
    stops = []
    for color, first, last in runs(colors):
        stops.append(f"{color} {(first - 1) / n * 100:.4f}% {last / n * 100:.4f}%")
    return "linear-gradient(to right,\n      " + ",\n      ".join(stops) + ")"


def block(colors: list[str]) -> str:
    return (
        f"  {BEGIN}\n"
        f"  section {{ --inno-progress-map: {gradient(colors)}; }}\n"
        f"  {END}\n"
    )


def inject(md: str, css: str) -> str:
    """Put the block inside the frontmatter's `style:` scalar, replacing any prior one."""
    fm = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", md, re.S)
    if not fm:
        sys.exit("No YAML frontmatter found — is this a Marp deck?")
    head, body = fm.group(1), md[fm.end():]

    # Drop a previous injection, markers included, wherever it sits.
    lines, keep, dropping = head.splitlines(), [], False
    for line in lines:
        if BEGIN in line:
            dropping = True
        if not dropping:
            keep.append(line)
        if END in line:
            dropping = False
    head = "\n".join(keep).rstrip("\n")

    if re.search(r"^style:\s*\|", head, re.M):
        # Append to the existing scalar — it is already the last key by convention,
        # and a `style: |` block runs to the end of the frontmatter anyway.
        head = head + "\n" + css.rstrip("\n")
    else:
        head = head + "\nstyle: |\n" + css.rstrip("\n")

    return f"---\n{head}\n---\n{body}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("slides", type=Path, help="path to the deck's slides.md")
    ap.add_argument("--html", type=Path, help="rendered HTML (default: slides.html beside it)")
    ap.add_argument("--print", action="store_true", dest="print_only",
                    help="print the CSS instead of writing it into the deck")
    args = ap.parse_args()

    html_path = args.html or args.slides.with_suffix(".html")
    if not html_path.exists():
        sys.exit(f"Missing {html_path} — render the deck to HTML first.")

    colors = slide_colors(html_path.read_text(encoding="utf-8"), palette())
    if not colors:
        sys.exit(f"No slides found in {html_path}.")

    css = block(colors)
    if args.print_only:
        print(css)
        return 0

    md = args.slides.read_text(encoding="utf-8")
    args.slides.write_text(inject(md, css), encoding="utf-8", newline="")

    sections = runs(colors)
    print(f"{len(colors)} slides, {len(sections)} sections -> {args.slides}")
    for color, first, last in sections:
        print(f"  {color:<20} slides {first}-{last}")
    print("Rebuild the deck for the map to take effect.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
